//
//  ProductWorker.swift
//  ProductApp
//
//  Created by Ерасыл Еркин on 03.06.2024.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ProductWorkerProtocol {
    func fetchProductData(completion: @escaping ([Product.ViewModel]) -> Void)
}

class ProductWorker: ProductWorkerProtocol {
    func fetchProductData(completion: @escaping ([Product.ViewModel]) -> Void) {
        let model = [
            Product.ViewModel(productTitle: "iPhone 15 Pro",
                              productImage: UIImage(named: "iPhone15pro"),
                              productAmount: "499990 KZT")
        ]
        completion(model)
    }
}
