//
//  ProductConfigurator.swift
//  ProductApp
//
//  Created by Ерасыл Еркин on 03.06.2024.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class ProductConfigurator {
    
    static let shared = ProductConfigurator()
    
    func configure(viewController: ProductViewController) {
        let presenter = ProductPresenter()
        let router = ProductRouter()
        let worker = ProductWorker()
        let interactor = ProductInteractor(worker: worker, presenter: presenter)
        
        viewController.interactor = interactor
        viewController.router = router
        
        interactor.presenter = presenter
        presenter.viewController = viewController
        
        router.viewController = viewController
        router.dataStore = interactor
    }
}
