//
//  FavoritesRouter.swift
//  ProductApp
//
//  Created by Ерасыл Еркин on 04.06.2024.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol FavoritesRoutingLogic {
    func pushToDetail(productData: Product.ViewModel)
}

protocol FavoritesDataPassing
{
    var dataStore: FavoritesDataStore? { get }
}

class FavoritesRouter: NSObject, FavoritesRoutingLogic, FavoritesDataPassing {
    weak var viewController: FavoritesViewController?
    var dataStore: FavoritesDataStore?
    
    func pushToDetail(productData: Product.ViewModel) {
        let vc = DetailsViewController(productData: productData)
        vc.hidesBottomBarWhenPushed = true
        viewController?.navigationController?.pushViewController(vc, animated: true)
    }
}
