//
//  FavoritesInteractor.swift
//  ProductApp
//
//  Created by Ерасыл Еркин on 04.06.2024.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol FavoritesBusinessLogic {
    func getProductData()
}

protocol FavoritesDataStore {
    
}

final class FavoritesInteractor: FavoritesBusinessLogic, FavoritesDataStore {
    var presenter: FavoritesPresentationLogic?
    var worker: FavoritesWorkerProtocol?
    
    init(worker: FavoritesWorkerProtocol, presenter: FavoritesPresentationLogic) {
        self.worker = worker
        self.presenter = presenter
    }
    
    func getProductData() {
        worker?.fetchProductData { [weak self] productData in
            print(productData)
            self?.presenter?.presentProductData(model: productData)
        }
    }
}
