//
//  FavoritesConfigurator.swift
//  ProductApp
//
//  Created by Ерасыл Еркин on 04.06.2024.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class FavoritesConfigurator {
    
    static let shared = FavoritesConfigurator()
    
    func configure(viewController: FavoritesViewController) {
        let presenter = FavoritesPresenter()
        let router = FavoritesRouter()
        let worker = FavoritesWorker()
        let interactor = FavoritesInteractor(worker: worker, presenter: presenter)
        
        viewController.interactor = interactor
        viewController.router = router
        
        interactor.presenter = presenter
        presenter.viewController = viewController
        
        router.viewController = viewController
        router.dataStore = interactor
    }
}
