//
//  DetailsRouter.swift
//  ProductApp
//
//  Created by Ерасыл Еркин on 04.06.2024.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import PanModal

protocol DetailsRoutingLogic {
    func presentBuyProduct(with productData: Product.ViewModel)
    func showSuccessScreen(success: Bool)
}

protocol DetailsDataPassing {
    var dataStore: DetailsDataStore? { get set }
}

final class DetailsRouter: NSObject, DetailsRoutingLogic, DetailsDataPassing {
    weak var viewController: DetailsViewController?
    var dataStore: DetailsDataStore?
    
    func presentBuyProduct(with productData: Product.ViewModel) {
        let vc = BuyProductViewController(productData: productData)
        vc.delegate = viewController
        viewController?.presentPanModal(vc)
    }
    
    func showSuccessScreen(success: Bool) {
        let vc = SuccessViewViewController(success: success)
        viewController?.navigationController?.pushViewController(vc, animated: true)
    }
}
