//
//  DetailsRouter.swift
//  ProductApp
//
//  Created by Ерасыл Еркин on 04.06.2024.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import PanModal

@objc protocol DetailsRoutingLogic {
    func presentBuyProduct()
}

protocol DetailsDataPassing {
    var dataStore: DetailsDataStore? { get set }
}

final class DetailsRouter: NSObject, DetailsRoutingLogic, DetailsDataPassing {
    weak var viewController: DetailsViewController?
    var dataStore: DetailsDataStore?
    
    func presentBuyProduct() {
        let vc = BuyProductViewController()
        viewController?.presentPanModal(vc)
    }
    
}
