//
//  DetailsInteractor.swift
//  ProductApp
//
//  Created by Ерасыл Еркин on 04.06.2024.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import CoreData

protocol DetailsBusinessLogic {
    
}

protocol DetailsDataStore {
    var productData: Product.ViewModel? { get set }
}

final class DetailsInteractor: DetailsDataStore {
    
    var productData: Product.ViewModel?
    var presenter: DetailsPresentationLogic?
    var worker: DetailsWorker?
    let context = (UIApplication.shared.delegate as! AppDelegate).persistentContainer.viewContext
}

extension DetailsInteractor: DetailsBusinessLogic {
    
}
