//
//  CoursesInteractor.swift
//  ProductApp
//
//  Created by Ерасыл Еркин on 03.06.2024.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CoursesBusinessLogic {
    func getCoursesData()
}

protocol CoursesDataStore {
    func getCoursesData()
}

final class CoursesInteractor: CoursesBusinessLogic, CoursesDataStore {
    var presenter: CoursesPresentationLogic?
    var worker: CoursesWorkerProtocol?
    
    init(worker: CoursesWorkerProtocol, presenter: CoursesPresentationLogic) {
        self.worker = worker
        self.presenter = presenter
    }
    
    func getCoursesData() {
        worker?.fetchCoursesData(completion: { courses in
            self.presenter?.presentCoursesData(viewModel: courses)
        })
    }
}
