//
//  CoursesModels.swift
//  ProductApp
//
//  Created by Ерасыл Еркин on 03.06.2024.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Courses {
    // MARK: Use cases
    struct Request {
    }
    struct Response {
    }
    struct ViewModel {
        let title: String
        let instructor: String
        let duration: String
        let image: String
        let amount: String
        let description: String
    }
    
}
