//
//  CoursesViewController.swift
//  ProductApp
//
//  Created by Ерасыл Еркин on 03.06.2024.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CoursesDisplayLogic: AnyObject {
    
}

final class CoursesViewController: UIViewController {
    
    // MARK: - Deps
    var interactor: CoursesBusinessLogic?
    var router: (NSObjectProtocol & CoursesRoutingLogic & CoursesDataPassing)?
    
    // MARK: - UI
    private lazy var tableView: UITableView = {
        let tableView = UITableView()
        tableView.registerCell(CoursesTableViewCell.self)
        tableView.dataSource = self
        tableView.delegate = self
        return tableView
    }()
    
    // MARK: - View lifecycle
    override func viewDidLoad() {
        super.viewDidLoad()
        setupViews()
        setupConstraints()
    }
    
    // MARK: - Setup Views
    private func setupViews() {
        CoursesConfigurator.shared.configure(viewController: self)
        view.backgroundColor = .systemGray6
    }
    
    // MARK: - Setup Constraints
    private func setupConstraints() {
        
    }
    
}

extension CoursesViewController: CoursesDisplayLogic {
    
}
